module.exports = {
  projects: [
    '<rootDir>/apps/heroes',
    '<rootDir>/libs/heroes/heroes-index',
    '<rootDir>/libs/shared/shell',
    '<rootDir>/libs/shared/ui',
    '<rootDir>/libs/shared/heroes/data-access',
    '<rootDir>/libs/heroes/heroes-detail',
    '<rootDir>/libs/shared/router',
    '<rootDir>/apps/data',
    '<rootDir>/libs/shared/notes/data-access',
    '<rootDir>/libs/shared/guides/data-access',
    '<rootDir>/libs/shared/builds/data-access',
    '<rootDir>/libs/shared/perks/data-access',
    '<rootDir>/libs/shared/gear/data-access',
    '<rootDir>/libs/shared/root-state',
    '<rootDir>/libs/shared/gear/gear',
    '<rootDir>/libs/shared/perks/perk',
    '<rootDir>/libs/shared/skills/data-access',
    '<rootDir>/libs/shared/data',
    '<rootDir>/libs/shared/gear/loadout-editor',
    '<rootDir>/apps/data-entry',
    '<rootDir>/libs/shared/named-sets/data-access',
    '<rootDir>/libs/shared/teams/data-access',
  ],
};
